server:
  port: 8090
  servlet:
    context-path: /resource-server-jwt

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung